#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 130
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 62
#define ALIAS_COUNT 0
#define TOKEN_COUNT 37
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 11
#define PRODUCTION_ID_COUNT 1

enum ts_symbol_identifiers {
  anon_sym_SEMI = 1,
  anon_sym_let = 2,
  anon_sym_COLON = 3,
  anon_sym_EQ = 4,
  anon_sym_return = 5,
  anon_sym_DOT = 6,
  anon_sym_CARET = 7,
  anon_sym_STAR = 8,
  anon_sym_SLASH = 9,
  anon_sym_PLUS = 10,
  anon_sym_DASH = 11,
  anon_sym_LT = 12,
  anon_sym_GT = 13,
  anon_sym_EQ_EQ = 14,
  anon_sym_LT_EQ = 15,
  anon_sym_GT_EQ = 16,
  anon_sym_BANG_EQ = 17,
  anon_sym_or = 18,
  anon_sym_and = 19,
  anon_sym_not = 20,
  anon_sym_LPAREN = 21,
  anon_sym_COMMA = 22,
  anon_sym_RPAREN = 23,
  anon_sym_do = 24,
  anon_sym_for = 25,
  anon_sym_in = 26,
  anon_sym_while = 27,
  anon_sym_if = 28,
  anon_sym_else = 29,
  anon_sym_LBRACE = 30,
  anon_sym_RBRACE = 31,
  anon_sym_function = 32,
  anon_sym_PIPE = 33,
  sym_identifier = 34,
  sym_number = 35,
  sym_string = 36,
  sym_source_file = 37,
  sym_program = 38,
  sym_statement = 39,
  sym_declaration = 40,
  sym_return_statement = 41,
  sym_expression = 42,
  sym_binary_expression = 43,
  sym_prefix = 44,
  sym_postfix = 45,
  sym_literal = 46,
  sym_for_loop = 47,
  sym_while_loop = 48,
  sym_if_expression = 49,
  sym_block = 50,
  sym_function_literal = 51,
  sym_object = 52,
  sym_type = 53,
  sym_union_type = 54,
  sym_type_literal = 55,
  aux_sym_program_repeat1 = 56,
  aux_sym_postfix_repeat1 = 57,
  aux_sym_if_expression_repeat1 = 58,
  aux_sym_function_literal_repeat1 = 59,
  aux_sym_object_repeat1 = 60,
  aux_sym_union_type_repeat1 = 61,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_SEMI] = ";",
  [anon_sym_let] = "let",
  [anon_sym_COLON] = ":",
  [anon_sym_EQ] = "=",
  [anon_sym_return] = "return",
  [anon_sym_DOT] = ".",
  [anon_sym_CARET] = "^",
  [anon_sym_STAR] = "*",
  [anon_sym_SLASH] = "/",
  [anon_sym_PLUS] = "+",
  [anon_sym_DASH] = "-",
  [anon_sym_LT] = "<",
  [anon_sym_GT] = ">",
  [anon_sym_EQ_EQ] = "==",
  [anon_sym_LT_EQ] = "<=",
  [anon_sym_GT_EQ] = ">=",
  [anon_sym_BANG_EQ] = "!=",
  [anon_sym_or] = "or",
  [anon_sym_and] = "and",
  [anon_sym_not] = "not",
  [anon_sym_LPAREN] = "(",
  [anon_sym_COMMA] = ",",
  [anon_sym_RPAREN] = ")",
  [anon_sym_do] = "do",
  [anon_sym_for] = "for",
  [anon_sym_in] = "in",
  [anon_sym_while] = "while",
  [anon_sym_if] = "if",
  [anon_sym_else] = "else",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_function] = "function",
  [anon_sym_PIPE] = "|",
  [sym_identifier] = "identifier",
  [sym_number] = "number",
  [sym_string] = "string",
  [sym_source_file] = "source_file",
  [sym_program] = "program",
  [sym_statement] = "statement",
  [sym_declaration] = "declaration",
  [sym_return_statement] = "return_statement",
  [sym_expression] = "expression",
  [sym_binary_expression] = "binary_expression",
  [sym_prefix] = "prefix",
  [sym_postfix] = "postfix",
  [sym_literal] = "literal",
  [sym_for_loop] = "for_loop",
  [sym_while_loop] = "while_loop",
  [sym_if_expression] = "if_expression",
  [sym_block] = "block",
  [sym_function_literal] = "function_literal",
  [sym_object] = "object",
  [sym_type] = "type",
  [sym_union_type] = "union_type",
  [sym_type_literal] = "type_literal",
  [aux_sym_program_repeat1] = "program_repeat1",
  [aux_sym_postfix_repeat1] = "postfix_repeat1",
  [aux_sym_if_expression_repeat1] = "if_expression_repeat1",
  [aux_sym_function_literal_repeat1] = "function_literal_repeat1",
  [aux_sym_object_repeat1] = "object_repeat1",
  [aux_sym_union_type_repeat1] = "union_type_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [anon_sym_let] = anon_sym_let,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_return] = anon_sym_return,
  [anon_sym_DOT] = anon_sym_DOT,
  [anon_sym_CARET] = anon_sym_CARET,
  [anon_sym_STAR] = anon_sym_STAR,
  [anon_sym_SLASH] = anon_sym_SLASH,
  [anon_sym_PLUS] = anon_sym_PLUS,
  [anon_sym_DASH] = anon_sym_DASH,
  [anon_sym_LT] = anon_sym_LT,
  [anon_sym_GT] = anon_sym_GT,
  [anon_sym_EQ_EQ] = anon_sym_EQ_EQ,
  [anon_sym_LT_EQ] = anon_sym_LT_EQ,
  [anon_sym_GT_EQ] = anon_sym_GT_EQ,
  [anon_sym_BANG_EQ] = anon_sym_BANG_EQ,
  [anon_sym_or] = anon_sym_or,
  [anon_sym_and] = anon_sym_and,
  [anon_sym_not] = anon_sym_not,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_do] = anon_sym_do,
  [anon_sym_for] = anon_sym_for,
  [anon_sym_in] = anon_sym_in,
  [anon_sym_while] = anon_sym_while,
  [anon_sym_if] = anon_sym_if,
  [anon_sym_else] = anon_sym_else,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_function] = anon_sym_function,
  [anon_sym_PIPE] = anon_sym_PIPE,
  [sym_identifier] = sym_identifier,
  [sym_number] = sym_number,
  [sym_string] = sym_string,
  [sym_source_file] = sym_source_file,
  [sym_program] = sym_program,
  [sym_statement] = sym_statement,
  [sym_declaration] = sym_declaration,
  [sym_return_statement] = sym_return_statement,
  [sym_expression] = sym_expression,
  [sym_binary_expression] = sym_binary_expression,
  [sym_prefix] = sym_prefix,
  [sym_postfix] = sym_postfix,
  [sym_literal] = sym_literal,
  [sym_for_loop] = sym_for_loop,
  [sym_while_loop] = sym_while_loop,
  [sym_if_expression] = sym_if_expression,
  [sym_block] = sym_block,
  [sym_function_literal] = sym_function_literal,
  [sym_object] = sym_object,
  [sym_type] = sym_type,
  [sym_union_type] = sym_union_type,
  [sym_type_literal] = sym_type_literal,
  [aux_sym_program_repeat1] = aux_sym_program_repeat1,
  [aux_sym_postfix_repeat1] = aux_sym_postfix_repeat1,
  [aux_sym_if_expression_repeat1] = aux_sym_if_expression_repeat1,
  [aux_sym_function_literal_repeat1] = aux_sym_function_literal_repeat1,
  [aux_sym_object_repeat1] = aux_sym_object_repeat1,
  [aux_sym_union_type_repeat1] = aux_sym_union_type_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_let] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_return] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_CARET] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_STAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PLUS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BANG_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_or] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_and] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_not] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_do] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_for] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_in] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_while] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_if] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_else] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_function] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PIPE] = {
    .visible = true,
    .named = false,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_program] = {
    .visible = true,
    .named = true,
  },
  [sym_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_declaration] = {
    .visible = true,
    .named = true,
  },
  [sym_return_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_binary_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_prefix] = {
    .visible = true,
    .named = true,
  },
  [sym_postfix] = {
    .visible = true,
    .named = true,
  },
  [sym_literal] = {
    .visible = true,
    .named = true,
  },
  [sym_for_loop] = {
    .visible = true,
    .named = true,
  },
  [sym_while_loop] = {
    .visible = true,
    .named = true,
  },
  [sym_if_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_block] = {
    .visible = true,
    .named = true,
  },
  [sym_function_literal] = {
    .visible = true,
    .named = true,
  },
  [sym_object] = {
    .visible = true,
    .named = true,
  },
  [sym_type] = {
    .visible = true,
    .named = true,
  },
  [sym_union_type] = {
    .visible = true,
    .named = true,
  },
  [sym_type_literal] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_program_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_postfix_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_if_expression_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_function_literal_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_object_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_union_type_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 74,
  [75] = 75,
  [76] = 76,
  [77] = 77,
  [78] = 78,
  [79] = 79,
  [80] = 80,
  [81] = 81,
  [82] = 82,
  [83] = 83,
  [84] = 84,
  [85] = 85,
  [86] = 86,
  [87] = 87,
  [88] = 88,
  [89] = 89,
  [90] = 90,
  [91] = 91,
  [92] = 92,
  [93] = 93,
  [94] = 94,
  [95] = 95,
  [96] = 96,
  [97] = 97,
  [98] = 98,
  [99] = 99,
  [100] = 100,
  [101] = 101,
  [102] = 102,
  [103] = 103,
  [104] = 104,
  [105] = 105,
  [106] = 106,
  [107] = 107,
  [108] = 108,
  [109] = 109,
  [110] = 110,
  [111] = 111,
  [112] = 112,
  [113] = 113,
  [114] = 114,
  [115] = 115,
  [116] = 116,
  [117] = 117,
  [118] = 118,
  [119] = 119,
  [120] = 120,
  [121] = 121,
  [122] = 122,
  [123] = 123,
  [124] = 124,
  [125] = 125,
  [126] = 126,
  [127] = 127,
  [128] = 128,
  [129] = 129,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(38);
      ADVANCE_MAP(
        '!', 5,
        '"', 4,
        '(', 62,
        ')', 64,
        '*', 48,
        '+', 50,
        ',', 63,
        '-', 51,
        '.', 46,
        '/', 49,
        ':', 42,
        ';', 39,
        '<', 52,
        '=', 43,
        '>', 53,
        '^', 47,
        'a', 18,
        'd', 22,
        'e', 16,
        'f', 23,
        'i', 12,
        'l', 8,
        'n', 24,
        'o', 26,
        'r', 11,
        'w', 13,
        '{', 75,
        '|', 79,
        '}', 76,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      END_STATE();
    case 1:
      ADVANCE_MAP(
        '"', 4,
        ')', 64,
        '-', 35,
        'd', 92,
        'f', 93,
        'i', 84,
        'n', 94,
        'w', 85,
        '{', 75,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(104);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(103);
      END_STATE();
    case 2:
      if (lookahead == '"') ADVANCE(4);
      if (lookahead == ')') ADVANCE(64);
      if (lookahead == '-') ADVANCE(35);
      if (lookahead == '}') ADVANCE(76);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(2);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(104);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(103);
      END_STATE();
    case 3:
      if (lookahead == '"') ADVANCE(4);
      if (lookahead == '-') ADVANCE(35);
      if (lookahead == 'd') ADVANCE(92);
      if (lookahead == 'f') ADVANCE(93);
      if (lookahead == 'i') ADVANCE(84);
      if (lookahead == 'w') ADVANCE(85);
      if (lookahead == '{') ADVANCE(75);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(3);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(104);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(103);
      END_STATE();
    case 4:
      if (lookahead == '"') ADVANCE(106);
      if (lookahead != 0) ADVANCE(4);
      END_STATE();
    case 5:
      if (lookahead == '=') ADVANCE(57);
      END_STATE();
    case 6:
      if (lookahead == 'c') ADVANCE(33);
      END_STATE();
    case 7:
      if (lookahead == 'd') ADVANCE(59);
      END_STATE();
    case 8:
      if (lookahead == 'e') ADVANCE(30);
      END_STATE();
    case 9:
      if (lookahead == 'e') ADVANCE(74);
      END_STATE();
    case 10:
      if (lookahead == 'e') ADVANCE(70);
      END_STATE();
    case 11:
      if (lookahead == 'e') ADVANCE(32);
      END_STATE();
    case 12:
      if (lookahead == 'f') ADVANCE(72);
      if (lookahead == 'n') ADVANCE(69);
      END_STATE();
    case 13:
      if (lookahead == 'h') ADVANCE(14);
      END_STATE();
    case 14:
      if (lookahead == 'i') ADVANCE(17);
      END_STATE();
    case 15:
      if (lookahead == 'i') ADVANCE(25);
      END_STATE();
    case 16:
      if (lookahead == 'l') ADVANCE(29);
      END_STATE();
    case 17:
      if (lookahead == 'l') ADVANCE(10);
      END_STATE();
    case 18:
      if (lookahead == 'n') ADVANCE(7);
      END_STATE();
    case 19:
      if (lookahead == 'n') ADVANCE(6);
      END_STATE();
    case 20:
      if (lookahead == 'n') ADVANCE(44);
      END_STATE();
    case 21:
      if (lookahead == 'n') ADVANCE(77);
      END_STATE();
    case 22:
      if (lookahead == 'o') ADVANCE(65);
      END_STATE();
    case 23:
      if (lookahead == 'o') ADVANCE(27);
      if (lookahead == 'u') ADVANCE(19);
      END_STATE();
    case 24:
      if (lookahead == 'o') ADVANCE(31);
      END_STATE();
    case 25:
      if (lookahead == 'o') ADVANCE(21);
      END_STATE();
    case 26:
      if (lookahead == 'r') ADVANCE(58);
      END_STATE();
    case 27:
      if (lookahead == 'r') ADVANCE(67);
      END_STATE();
    case 28:
      if (lookahead == 'r') ADVANCE(20);
      END_STATE();
    case 29:
      if (lookahead == 's') ADVANCE(9);
      END_STATE();
    case 30:
      if (lookahead == 't') ADVANCE(40);
      END_STATE();
    case 31:
      if (lookahead == 't') ADVANCE(60);
      END_STATE();
    case 32:
      if (lookahead == 't') ADVANCE(34);
      END_STATE();
    case 33:
      if (lookahead == 't') ADVANCE(15);
      END_STATE();
    case 34:
      if (lookahead == 'u') ADVANCE(28);
      END_STATE();
    case 35:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(104);
      END_STATE();
    case 36:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(105);
      END_STATE();
    case 37:
      if (eof) ADVANCE(38);
      ADVANCE_MAP(
        '"', 4,
        '-', 35,
        'd', 92,
        'f', 93,
        'i', 84,
        'l', 81,
        'n', 94,
        'r', 83,
        'w', 85,
        '{', 75,
        '}', 76,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(37);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(104);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(103);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(anon_sym_let);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(anon_sym_let);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(103);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(anon_sym_EQ);
      if (lookahead == '=') ADVANCE(54);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(anon_sym_return);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(anon_sym_return);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(103);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(anon_sym_DOT);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(anon_sym_CARET);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(anon_sym_STAR);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(anon_sym_SLASH);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(anon_sym_PLUS);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(anon_sym_DASH);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(anon_sym_LT);
      if (lookahead == '=') ADVANCE(55);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(anon_sym_GT);
      if (lookahead == '=') ADVANCE(56);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(anon_sym_EQ_EQ);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(anon_sym_LT_EQ);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(anon_sym_GT_EQ);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(anon_sym_BANG_EQ);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(anon_sym_or);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(anon_sym_and);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(anon_sym_not);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(anon_sym_not);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(103);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(anon_sym_do);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(anon_sym_do);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(103);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(anon_sym_for);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(anon_sym_for);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(103);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(anon_sym_in);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(anon_sym_while);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(anon_sym_while);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(103);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(anon_sym_if);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(anon_sym_if);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(103);
      END_STATE();
    case 74:
      ACCEPT_TOKEN(anon_sym_else);
      END_STATE();
    case 75:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 76:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 77:
      ACCEPT_TOKEN(anon_sym_function);
      END_STATE();
    case 78:
      ACCEPT_TOKEN(anon_sym_function);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(103);
      END_STATE();
    case 79:
      ACCEPT_TOKEN(anon_sym_PIPE);
      END_STATE();
    case 80:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'c') ADVANCE(101);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(103);
      END_STATE();
    case 81:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(98);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(103);
      END_STATE();
    case 82:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(71);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(103);
      END_STATE();
    case 83:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(100);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(103);
      END_STATE();
    case 84:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'f') ADVANCE(73);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(103);
      END_STATE();
    case 85:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'h') ADVANCE(86);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(103);
      END_STATE();
    case 86:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'i') ADVANCE(88);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(103);
      END_STATE();
    case 87:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'i') ADVANCE(95);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(103);
      END_STATE();
    case 88:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'l') ADVANCE(82);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(103);
      END_STATE();
    case 89:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'n') ADVANCE(80);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(103);
      END_STATE();
    case 90:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'n') ADVANCE(45);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(103);
      END_STATE();
    case 91:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'n') ADVANCE(78);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(103);
      END_STATE();
    case 92:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'o') ADVANCE(66);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(103);
      END_STATE();
    case 93:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'o') ADVANCE(96);
      if (lookahead == 'u') ADVANCE(89);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(103);
      END_STATE();
    case 94:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'o') ADVANCE(99);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(103);
      END_STATE();
    case 95:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'o') ADVANCE(91);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(103);
      END_STATE();
    case 96:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'r') ADVANCE(68);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(103);
      END_STATE();
    case 97:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'r') ADVANCE(90);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(103);
      END_STATE();
    case 98:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 't') ADVANCE(41);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(103);
      END_STATE();
    case 99:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 't') ADVANCE(61);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(103);
      END_STATE();
    case 100:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 't') ADVANCE(102);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(103);
      END_STATE();
    case 101:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 't') ADVANCE(87);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(103);
      END_STATE();
    case 102:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'u') ADVANCE(97);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(103);
      END_STATE();
    case 103:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(103);
      END_STATE();
    case 104:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '.') ADVANCE(36);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(104);
      END_STATE();
    case 105:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(105);
      END_STATE();
    case 106:
      ACCEPT_TOKEN(sym_string);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 37},
  [2] = {.lex_state = 37},
  [3] = {.lex_state = 37},
  [4] = {.lex_state = 37},
  [5] = {.lex_state = 37},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 1},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 1},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 1},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 1},
  [31] = {.lex_state = 1},
  [32] = {.lex_state = 1},
  [33] = {.lex_state = 1},
  [34] = {.lex_state = 1},
  [35] = {.lex_state = 1},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 1},
  [41] = {.lex_state = 1},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 1},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 1},
  [47] = {.lex_state = 1},
  [48] = {.lex_state = 1},
  [49] = {.lex_state = 1},
  [50] = {.lex_state = 1},
  [51] = {.lex_state = 1},
  [52] = {.lex_state = 1},
  [53] = {.lex_state = 3},
  [54] = {.lex_state = 37},
  [55] = {.lex_state = 2},
  [56] = {.lex_state = 2},
  [57] = {.lex_state = 2},
  [58] = {.lex_state = 0},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 2},
  [61] = {.lex_state = 0},
  [62] = {.lex_state = 2},
  [63] = {.lex_state = 2},
  [64] = {.lex_state = 2},
  [65] = {.lex_state = 0},
  [66] = {.lex_state = 0},
  [67] = {.lex_state = 0},
  [68] = {.lex_state = 0},
  [69] = {.lex_state = 0},
  [70] = {.lex_state = 0},
  [71] = {.lex_state = 0},
  [72] = {.lex_state = 0},
  [73] = {.lex_state = 0},
  [74] = {.lex_state = 0},
  [75] = {.lex_state = 0},
  [76] = {.lex_state = 2},
  [77] = {.lex_state = 0},
  [78] = {.lex_state = 0},
  [79] = {.lex_state = 0},
  [80] = {.lex_state = 0},
  [81] = {.lex_state = 0},
  [82] = {.lex_state = 0},
  [83] = {.lex_state = 0},
  [84] = {.lex_state = 0},
  [85] = {.lex_state = 0},
  [86] = {.lex_state = 0},
  [87] = {.lex_state = 0},
  [88] = {.lex_state = 2},
  [89] = {.lex_state = 2},
  [90] = {.lex_state = 0},
  [91] = {.lex_state = 0},
  [92] = {.lex_state = 2},
  [93] = {.lex_state = 2},
  [94] = {.lex_state = 2},
  [95] = {.lex_state = 0},
  [96] = {.lex_state = 0},
  [97] = {.lex_state = 0},
  [98] = {.lex_state = 0},
  [99] = {.lex_state = 2},
  [100] = {.lex_state = 0},
  [101] = {.lex_state = 0},
  [102] = {.lex_state = 0},
  [103] = {.lex_state = 0},
  [104] = {.lex_state = 0},
  [105] = {.lex_state = 0},
  [106] = {.lex_state = 0},
  [107] = {.lex_state = 2},
  [108] = {.lex_state = 0},
  [109] = {.lex_state = 0},
  [110] = {.lex_state = 0},
  [111] = {.lex_state = 2},
  [112] = {.lex_state = 0},
  [113] = {.lex_state = 0},
  [114] = {.lex_state = 0},
  [115] = {.lex_state = 0},
  [116] = {.lex_state = 0},
  [117] = {.lex_state = 0},
  [118] = {.lex_state = 0},
  [119] = {.lex_state = 0},
  [120] = {.lex_state = 0},
  [121] = {.lex_state = 0},
  [122] = {.lex_state = 2},
  [123] = {.lex_state = 0},
  [124] = {.lex_state = 0},
  [125] = {.lex_state = 2},
  [126] = {.lex_state = 0},
  [127] = {.lex_state = 0},
  [128] = {.lex_state = 2},
  [129] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_SEMI] = ACTIONS(1),
    [anon_sym_let] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_return] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [anon_sym_CARET] = ACTIONS(1),
    [anon_sym_STAR] = ACTIONS(1),
    [anon_sym_SLASH] = ACTIONS(1),
    [anon_sym_PLUS] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [anon_sym_EQ_EQ] = ACTIONS(1),
    [anon_sym_LT_EQ] = ACTIONS(1),
    [anon_sym_GT_EQ] = ACTIONS(1),
    [anon_sym_BANG_EQ] = ACTIONS(1),
    [anon_sym_or] = ACTIONS(1),
    [anon_sym_and] = ACTIONS(1),
    [anon_sym_not] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_do] = ACTIONS(1),
    [anon_sym_for] = ACTIONS(1),
    [anon_sym_in] = ACTIONS(1),
    [anon_sym_while] = ACTIONS(1),
    [anon_sym_if] = ACTIONS(1),
    [anon_sym_else] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_function] = ACTIONS(1),
    [anon_sym_PIPE] = ACTIONS(1),
    [sym_string] = ACTIONS(1),
  },
  [1] = {
    [sym_source_file] = STATE(119),
    [sym_program] = STATE(120),
    [sym_statement] = STATE(4),
    [sym_declaration] = STATE(117),
    [sym_return_statement] = STATE(117),
    [sym_expression] = STATE(117),
    [sym_binary_expression] = STATE(74),
    [sym_prefix] = STATE(37),
    [sym_postfix] = STATE(38),
    [sym_literal] = STATE(13),
    [sym_for_loop] = STATE(14),
    [sym_while_loop] = STATE(14),
    [sym_if_expression] = STATE(14),
    [sym_function_literal] = STATE(14),
    [sym_object] = STATE(14),
    [aux_sym_program_repeat1] = STATE(4),
    [anon_sym_let] = ACTIONS(3),
    [anon_sym_return] = ACTIONS(5),
    [anon_sym_not] = ACTIONS(7),
    [anon_sym_do] = ACTIONS(9),
    [anon_sym_for] = ACTIONS(11),
    [anon_sym_while] = ACTIONS(13),
    [anon_sym_if] = ACTIONS(15),
    [anon_sym_LBRACE] = ACTIONS(17),
    [anon_sym_function] = ACTIONS(19),
    [sym_identifier] = ACTIONS(21),
    [sym_number] = ACTIONS(23),
    [sym_string] = ACTIONS(23),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 19,
    ACTIONS(27), 1,
      anon_sym_let,
    ACTIONS(30), 1,
      anon_sym_return,
    ACTIONS(33), 1,
      anon_sym_not,
    ACTIONS(36), 1,
      anon_sym_do,
    ACTIONS(39), 1,
      anon_sym_for,
    ACTIONS(42), 1,
      anon_sym_while,
    ACTIONS(45), 1,
      anon_sym_if,
    ACTIONS(48), 1,
      anon_sym_LBRACE,
    ACTIONS(51), 1,
      anon_sym_function,
    ACTIONS(54), 1,
      sym_identifier,
    STATE(13), 1,
      sym_literal,
    STATE(37), 1,
      sym_prefix,
    STATE(38), 1,
      sym_postfix,
    STATE(74), 1,
      sym_binary_expression,
    ACTIONS(25), 2,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
    ACTIONS(57), 2,
      sym_number,
      sym_string,
    STATE(2), 2,
      sym_statement,
      aux_sym_program_repeat1,
    STATE(117), 3,
      sym_declaration,
      sym_return_statement,
      sym_expression,
    STATE(14), 5,
      sym_for_loop,
      sym_while_loop,
      sym_if_expression,
      sym_function_literal,
      sym_object,
  [67] = 19,
    ACTIONS(3), 1,
      anon_sym_let,
    ACTIONS(5), 1,
      anon_sym_return,
    ACTIONS(7), 1,
      anon_sym_not,
    ACTIONS(9), 1,
      anon_sym_do,
    ACTIONS(11), 1,
      anon_sym_for,
    ACTIONS(13), 1,
      anon_sym_while,
    ACTIONS(15), 1,
      anon_sym_if,
    ACTIONS(17), 1,
      anon_sym_LBRACE,
    ACTIONS(19), 1,
      anon_sym_function,
    ACTIONS(21), 1,
      sym_identifier,
    ACTIONS(60), 1,
      anon_sym_RBRACE,
    STATE(13), 1,
      sym_literal,
    STATE(37), 1,
      sym_prefix,
    STATE(38), 1,
      sym_postfix,
    STATE(74), 1,
      sym_binary_expression,
    ACTIONS(23), 2,
      sym_number,
      sym_string,
    STATE(2), 2,
      sym_statement,
      aux_sym_program_repeat1,
    STATE(117), 3,
      sym_declaration,
      sym_return_statement,
      sym_expression,
    STATE(14), 5,
      sym_for_loop,
      sym_while_loop,
      sym_if_expression,
      sym_function_literal,
      sym_object,
  [133] = 19,
    ACTIONS(3), 1,
      anon_sym_let,
    ACTIONS(5), 1,
      anon_sym_return,
    ACTIONS(7), 1,
      anon_sym_not,
    ACTIONS(9), 1,
      anon_sym_do,
    ACTIONS(11), 1,
      anon_sym_for,
    ACTIONS(13), 1,
      anon_sym_while,
    ACTIONS(15), 1,
      anon_sym_if,
    ACTIONS(17), 1,
      anon_sym_LBRACE,
    ACTIONS(19), 1,
      anon_sym_function,
    ACTIONS(21), 1,
      sym_identifier,
    ACTIONS(62), 1,
      ts_builtin_sym_end,
    STATE(13), 1,
      sym_literal,
    STATE(37), 1,
      sym_prefix,
    STATE(38), 1,
      sym_postfix,
    STATE(74), 1,
      sym_binary_expression,
    ACTIONS(23), 2,
      sym_number,
      sym_string,
    STATE(2), 2,
      sym_statement,
      aux_sym_program_repeat1,
    STATE(117), 3,
      sym_declaration,
      sym_return_statement,
      sym_expression,
    STATE(14), 5,
      sym_for_loop,
      sym_while_loop,
      sym_if_expression,
      sym_function_literal,
      sym_object,
  [199] = 19,
    ACTIONS(3), 1,
      anon_sym_let,
    ACTIONS(5), 1,
      anon_sym_return,
    ACTIONS(7), 1,
      anon_sym_not,
    ACTIONS(9), 1,
      anon_sym_do,
    ACTIONS(11), 1,
      anon_sym_for,
    ACTIONS(13), 1,
      anon_sym_while,
    ACTIONS(15), 1,
      anon_sym_if,
    ACTIONS(17), 1,
      anon_sym_LBRACE,
    ACTIONS(19), 1,
      anon_sym_function,
    ACTIONS(21), 1,
      sym_identifier,
    ACTIONS(64), 1,
      anon_sym_RBRACE,
    STATE(13), 1,
      sym_literal,
    STATE(37), 1,
      sym_prefix,
    STATE(38), 1,
      sym_postfix,
    STATE(74), 1,
      sym_binary_expression,
    ACTIONS(23), 2,
      sym_number,
      sym_string,
    STATE(3), 2,
      sym_statement,
      aux_sym_program_repeat1,
    STATE(117), 3,
      sym_declaration,
      sym_return_statement,
      sym_expression,
    STATE(14), 5,
      sym_for_loop,
      sym_while_loop,
      sym_if_expression,
      sym_function_literal,
      sym_object,
  [265] = 4,
    ACTIONS(70), 1,
      anon_sym_else,
    STATE(7), 1,
      aux_sym_if_expression_repeat1,
    ACTIONS(68), 3,
      anon_sym_EQ,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(66), 18,
      anon_sym_SEMI,
      anon_sym_DOT,
      anon_sym_CARET,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_EQ_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_BANG_EQ,
      anon_sym_or,
      anon_sym_and,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
  [297] = 4,
    ACTIONS(76), 1,
      anon_sym_else,
    STATE(8), 1,
      aux_sym_if_expression_repeat1,
    ACTIONS(74), 3,
      anon_sym_EQ,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(72), 18,
      anon_sym_SEMI,
      anon_sym_DOT,
      anon_sym_CARET,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_EQ_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_BANG_EQ,
      anon_sym_or,
      anon_sym_and,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
  [329] = 4,
    ACTIONS(82), 1,
      anon_sym_else,
    STATE(8), 1,
      aux_sym_if_expression_repeat1,
    ACTIONS(80), 3,
      anon_sym_EQ,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(78), 18,
      anon_sym_SEMI,
      anon_sym_DOT,
      anon_sym_CARET,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_EQ_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_BANG_EQ,
      anon_sym_or,
      anon_sym_and,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
  [361] = 2,
    ACTIONS(87), 3,
      anon_sym_EQ,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(85), 19,
      anon_sym_SEMI,
      anon_sym_DOT,
      anon_sym_CARET,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_EQ_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_BANG_EQ,
      anon_sym_or,
      anon_sym_and,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_else,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
  [388] = 2,
    ACTIONS(91), 3,
      anon_sym_EQ,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(89), 19,
      anon_sym_SEMI,
      anon_sym_DOT,
      anon_sym_CARET,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_EQ_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_BANG_EQ,
      anon_sym_or,
      anon_sym_and,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_else,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
  [415] = 2,
    ACTIONS(95), 3,
      anon_sym_EQ,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(93), 19,
      anon_sym_SEMI,
      anon_sym_DOT,
      anon_sym_CARET,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_EQ_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_BANG_EQ,
      anon_sym_or,
      anon_sym_and,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_else,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
  [442] = 2,
    ACTIONS(99), 3,
      anon_sym_EQ,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(97), 18,
      anon_sym_SEMI,
      anon_sym_DOT,
      anon_sym_CARET,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_EQ_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_BANG_EQ,
      anon_sym_or,
      anon_sym_and,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
  [468] = 3,
    ACTIONS(105), 1,
      anon_sym_LPAREN,
    ACTIONS(103), 3,
      anon_sym_EQ,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(101), 17,
      anon_sym_SEMI,
      anon_sym_DOT,
      anon_sym_CARET,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_EQ_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_BANG_EQ,
      anon_sym_or,
      anon_sym_and,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
  [496] = 2,
    ACTIONS(109), 3,
      anon_sym_EQ,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(107), 18,
      anon_sym_SEMI,
      anon_sym_DOT,
      anon_sym_CARET,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_EQ_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_BANG_EQ,
      anon_sym_or,
      anon_sym_and,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
  [522] = 16,
    ACTIONS(7), 1,
      anon_sym_not,
    ACTIONS(9), 1,
      anon_sym_do,
    ACTIONS(11), 1,
      anon_sym_for,
    ACTIONS(13), 1,
      anon_sym_while,
    ACTIONS(15), 1,
      anon_sym_if,
    ACTIONS(17), 1,
      anon_sym_LBRACE,
    ACTIONS(19), 1,
      anon_sym_function,
    ACTIONS(21), 1,
      sym_identifier,
    ACTIONS(111), 1,
      anon_sym_RPAREN,
    STATE(13), 1,
      sym_literal,
    STATE(37), 1,
      sym_prefix,
    STATE(38), 1,
      sym_postfix,
    STATE(74), 1,
      sym_binary_expression,
    STATE(77), 1,
      sym_expression,
    ACTIONS(23), 2,
      sym_number,
      sym_string,
    STATE(14), 5,
      sym_for_loop,
      sym_while_loop,
      sym_if_expression,
      sym_function_literal,
      sym_object,
  [576] = 2,
    ACTIONS(115), 3,
      anon_sym_EQ,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(113), 18,
      anon_sym_SEMI,
      anon_sym_DOT,
      anon_sym_CARET,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_EQ_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_BANG_EQ,
      anon_sym_or,
      anon_sym_and,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
  [602] = 2,
    ACTIONS(119), 3,
      anon_sym_EQ,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(117), 18,
      anon_sym_SEMI,
      anon_sym_DOT,
      anon_sym_CARET,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_EQ_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_BANG_EQ,
      anon_sym_or,
      anon_sym_and,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
  [628] = 2,
    ACTIONS(123), 3,
      anon_sym_EQ,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(121), 18,
      anon_sym_SEMI,
      anon_sym_DOT,
      anon_sym_CARET,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_EQ_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_BANG_EQ,
      anon_sym_or,
      anon_sym_and,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
  [654] = 2,
    ACTIONS(127), 3,
      anon_sym_EQ,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(125), 18,
      anon_sym_SEMI,
      anon_sym_DOT,
      anon_sym_CARET,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_EQ_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_BANG_EQ,
      anon_sym_or,
      anon_sym_and,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
  [680] = 2,
    ACTIONS(131), 3,
      anon_sym_EQ,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(129), 18,
      anon_sym_SEMI,
      anon_sym_DOT,
      anon_sym_CARET,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_EQ_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_BANG_EQ,
      anon_sym_or,
      anon_sym_and,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
  [706] = 16,
    ACTIONS(7), 1,
      anon_sym_not,
    ACTIONS(9), 1,
      anon_sym_do,
    ACTIONS(11), 1,
      anon_sym_for,
    ACTIONS(13), 1,
      anon_sym_while,
    ACTIONS(15), 1,
      anon_sym_if,
    ACTIONS(17), 1,
      anon_sym_LBRACE,
    ACTIONS(19), 1,
      anon_sym_function,
    ACTIONS(21), 1,
      sym_identifier,
    ACTIONS(133), 1,
      anon_sym_RPAREN,
    STATE(13), 1,
      sym_literal,
    STATE(37), 1,
      sym_prefix,
    STATE(38), 1,
      sym_postfix,
    STATE(74), 1,
      sym_binary_expression,
    STATE(97), 1,
      sym_expression,
    ACTIONS(23), 2,
      sym_number,
      sym_string,
    STATE(14), 5,
      sym_for_loop,
      sym_while_loop,
      sym_if_expression,
      sym_function_literal,
      sym_object,
  [760] = 2,
    ACTIONS(137), 3,
      anon_sym_EQ,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(135), 18,
      anon_sym_SEMI,
      anon_sym_DOT,
      anon_sym_CARET,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_EQ_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_BANG_EQ,
      anon_sym_or,
      anon_sym_and,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
  [786] = 2,
    ACTIONS(141), 3,
      anon_sym_EQ,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(139), 18,
      anon_sym_SEMI,
      anon_sym_DOT,
      anon_sym_CARET,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_EQ_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_BANG_EQ,
      anon_sym_or,
      anon_sym_and,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
  [812] = 2,
    ACTIONS(145), 3,
      anon_sym_EQ,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(143), 18,
      anon_sym_SEMI,
      anon_sym_DOT,
      anon_sym_CARET,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_EQ_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_BANG_EQ,
      anon_sym_or,
      anon_sym_and,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
  [838] = 16,
    ACTIONS(7), 1,
      anon_sym_not,
    ACTIONS(9), 1,
      anon_sym_do,
    ACTIONS(11), 1,
      anon_sym_for,
    ACTIONS(13), 1,
      anon_sym_while,
    ACTIONS(15), 1,
      anon_sym_if,
    ACTIONS(17), 1,
      anon_sym_LBRACE,
    ACTIONS(19), 1,
      anon_sym_function,
    ACTIONS(21), 1,
      sym_identifier,
    ACTIONS(147), 1,
      anon_sym_RPAREN,
    STATE(13), 1,
      sym_literal,
    STATE(37), 1,
      sym_prefix,
    STATE(38), 1,
      sym_postfix,
    STATE(74), 1,
      sym_binary_expression,
    STATE(97), 1,
      sym_expression,
    ACTIONS(23), 2,
      sym_number,
      sym_string,
    STATE(14), 5,
      sym_for_loop,
      sym_while_loop,
      sym_if_expression,
      sym_function_literal,
      sym_object,
  [892] = 2,
    ACTIONS(151), 3,
      anon_sym_EQ,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(149), 18,
      anon_sym_SEMI,
      anon_sym_DOT,
      anon_sym_CARET,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_EQ_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_BANG_EQ,
      anon_sym_or,
      anon_sym_and,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
  [918] = 2,
    ACTIONS(155), 3,
      anon_sym_EQ,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(153), 18,
      anon_sym_SEMI,
      anon_sym_DOT,
      anon_sym_CARET,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_EQ_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_BANG_EQ,
      anon_sym_or,
      anon_sym_and,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
  [944] = 2,
    ACTIONS(159), 3,
      anon_sym_EQ,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(157), 18,
      anon_sym_SEMI,
      anon_sym_DOT,
      anon_sym_CARET,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_EQ_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_BANG_EQ,
      anon_sym_or,
      anon_sym_and,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
  [970] = 2,
    ACTIONS(163), 3,
      anon_sym_EQ,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(161), 18,
      anon_sym_SEMI,
      anon_sym_DOT,
      anon_sym_CARET,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_EQ_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_BANG_EQ,
      anon_sym_or,
      anon_sym_and,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
  [996] = 15,
    ACTIONS(7), 1,
      anon_sym_not,
    ACTIONS(9), 1,
      anon_sym_do,
    ACTIONS(11), 1,
      anon_sym_for,
    ACTIONS(13), 1,
      anon_sym_while,
    ACTIONS(15), 1,
      anon_sym_if,
    ACTIONS(17), 1,
      anon_sym_LBRACE,
    ACTIONS(19), 1,
      anon_sym_function,
    ACTIONS(21), 1,
      sym_identifier,
    STATE(13), 1,
      sym_literal,
    STATE(37), 1,
      sym_prefix,
    STATE(38), 1,
      sym_postfix,
    STATE(74), 1,
      sym_binary_expression,
    STATE(98), 1,
      sym_expression,
    ACTIONS(23), 2,
      sym_number,
      sym_string,
    STATE(14), 5,
      sym_for_loop,
      sym_while_loop,
      sym_if_expression,
      sym_function_literal,
      sym_object,
  [1047] = 15,
    ACTIONS(7), 1,
      anon_sym_not,
    ACTIONS(9), 1,
      anon_sym_do,
    ACTIONS(11), 1,
      anon_sym_for,
    ACTIONS(13), 1,
      anon_sym_while,
    ACTIONS(15), 1,
      anon_sym_if,
    ACTIONS(17), 1,
      anon_sym_LBRACE,
    ACTIONS(19), 1,
      anon_sym_function,
    ACTIONS(21), 1,
      sym_identifier,
    STATE(13), 1,
      sym_literal,
    STATE(37), 1,
      sym_prefix,
    STATE(38), 1,
      sym_postfix,
    STATE(74), 1,
      sym_binary_expression,
    STATE(100), 1,
      sym_expression,
    ACTIONS(23), 2,
      sym_number,
      sym_string,
    STATE(14), 5,
      sym_for_loop,
      sym_while_loop,
      sym_if_expression,
      sym_function_literal,
      sym_object,
  [1098] = 15,
    ACTIONS(7), 1,
      anon_sym_not,
    ACTIONS(9), 1,
      anon_sym_do,
    ACTIONS(11), 1,
      anon_sym_for,
    ACTIONS(13), 1,
      anon_sym_while,
    ACTIONS(15), 1,
      anon_sym_if,
    ACTIONS(17), 1,
      anon_sym_LBRACE,
    ACTIONS(19), 1,
      anon_sym_function,
    ACTIONS(21), 1,
      sym_identifier,
    STATE(13), 1,
      sym_literal,
    STATE(37), 1,
      sym_prefix,
    STATE(38), 1,
      sym_postfix,
    STATE(74), 1,
      sym_binary_expression,
    STATE(114), 1,
      sym_expression,
    ACTIONS(23), 2,
      sym_number,
      sym_string,
    STATE(14), 5,
      sym_for_loop,
      sym_while_loop,
      sym_if_expression,
      sym_function_literal,
      sym_object,
  [1149] = 15,
    ACTIONS(7), 1,
      anon_sym_not,
    ACTIONS(9), 1,
      anon_sym_do,
    ACTIONS(11), 1,
      anon_sym_for,
    ACTIONS(13), 1,
      anon_sym_while,
    ACTIONS(15), 1,
      anon_sym_if,
    ACTIONS(17), 1,
      anon_sym_LBRACE,
    ACTIONS(19), 1,
      anon_sym_function,
    ACTIONS(21), 1,
      sym_identifier,
    STATE(13), 1,
      sym_literal,
    STATE(37), 1,
      sym_prefix,
    STATE(38), 1,
      sym_postfix,
    STATE(74), 1,
      sym_binary_expression,
    STATE(115), 1,
      sym_expression,
    ACTIONS(23), 2,
      sym_number,
      sym_string,
    STATE(14), 5,
      sym_for_loop,
      sym_while_loop,
      sym_if_expression,
      sym_function_literal,
      sym_object,
  [1200] = 15,
    ACTIONS(7), 1,
      anon_sym_not,
    ACTIONS(9), 1,
      anon_sym_do,
    ACTIONS(11), 1,
      anon_sym_for,
    ACTIONS(13), 1,
      anon_sym_while,
    ACTIONS(15), 1,
      anon_sym_if,
    ACTIONS(17), 1,
      anon_sym_LBRACE,
    ACTIONS(19), 1,
      anon_sym_function,
    ACTIONS(21), 1,
      sym_identifier,
    STATE(13), 1,
      sym_literal,
    STATE(37), 1,
      sym_prefix,
    STATE(38), 1,
      sym_postfix,
    STATE(74), 1,
      sym_binary_expression,
    STATE(91), 1,
      sym_expression,
    ACTIONS(23), 2,
      sym_number,
      sym_string,
    STATE(14), 5,
      sym_for_loop,
      sym_while_loop,
      sym_if_expression,
      sym_function_literal,
      sym_object,
  [1251] = 15,
    ACTIONS(7), 1,
      anon_sym_not,
    ACTIONS(9), 1,
      anon_sym_do,
    ACTIONS(11), 1,
      anon_sym_for,
    ACTIONS(13), 1,
      anon_sym_while,
    ACTIONS(15), 1,
      anon_sym_if,
    ACTIONS(17), 1,
      anon_sym_LBRACE,
    ACTIONS(19), 1,
      anon_sym_function,
    ACTIONS(21), 1,
      sym_identifier,
    STATE(13), 1,
      sym_literal,
    STATE(37), 1,
      sym_prefix,
    STATE(38), 1,
      sym_postfix,
    STATE(74), 1,
      sym_binary_expression,
    STATE(84), 1,
      sym_expression,
    ACTIONS(23), 2,
      sym_number,
      sym_string,
    STATE(14), 5,
      sym_for_loop,
      sym_while_loop,
      sym_if_expression,
      sym_function_literal,
      sym_object,
  [1302] = 2,
    ACTIONS(167), 3,
      anon_sym_EQ,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(165), 17,
      anon_sym_SEMI,
      anon_sym_DOT,
      anon_sym_CARET,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_EQ_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_BANG_EQ,
      anon_sym_or,
      anon_sym_and,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
  [1327] = 9,
    ACTIONS(171), 1,
      anon_sym_EQ,
    ACTIONS(173), 1,
      anon_sym_DOT,
    ACTIONS(175), 1,
      anon_sym_CARET,
    ACTIONS(177), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(179), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(181), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(185), 2,
      anon_sym_or,
      anon_sym_and,
    ACTIONS(183), 4,
      anon_sym_EQ_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_BANG_EQ,
    ACTIONS(169), 5,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
  [1366] = 2,
    ACTIONS(189), 3,
      anon_sym_EQ,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(187), 17,
      anon_sym_SEMI,
      anon_sym_DOT,
      anon_sym_CARET,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_EQ_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_BANG_EQ,
      anon_sym_or,
      anon_sym_and,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
  [1391] = 2,
    ACTIONS(193), 3,
      anon_sym_EQ,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(191), 17,
      anon_sym_SEMI,
      anon_sym_DOT,
      anon_sym_CARET,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_EQ_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_BANG_EQ,
      anon_sym_or,
      anon_sym_and,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
  [1416] = 15,
    ACTIONS(7), 1,
      anon_sym_not,
    ACTIONS(9), 1,
      anon_sym_do,
    ACTIONS(11), 1,
      anon_sym_for,
    ACTIONS(13), 1,
      anon_sym_while,
    ACTIONS(15), 1,
      anon_sym_if,
    ACTIONS(17), 1,
      anon_sym_LBRACE,
    ACTIONS(19), 1,
      anon_sym_function,
    ACTIONS(21), 1,
      sym_identifier,
    STATE(13), 1,
      sym_literal,
    STATE(37), 1,
      sym_prefix,
    STATE(38), 1,
      sym_postfix,
    STATE(74), 1,
      sym_binary_expression,
    STATE(109), 1,
      sym_expression,
    ACTIONS(23), 2,
      sym_number,
      sym_string,
    STATE(14), 5,
      sym_for_loop,
      sym_while_loop,
      sym_if_expression,
      sym_function_literal,
      sym_object,
  [1467] = 15,
    ACTIONS(7), 1,
      anon_sym_not,
    ACTIONS(9), 1,
      anon_sym_do,
    ACTIONS(11), 1,
      anon_sym_for,
    ACTIONS(13), 1,
      anon_sym_while,
    ACTIONS(15), 1,
      anon_sym_if,
    ACTIONS(17), 1,
      anon_sym_LBRACE,
    ACTIONS(19), 1,
      anon_sym_function,
    ACTIONS(21), 1,
      sym_identifier,
    STATE(13), 1,
      sym_literal,
    STATE(37), 1,
      sym_prefix,
    STATE(38), 1,
      sym_postfix,
    STATE(74), 1,
      sym_binary_expression,
    STATE(90), 1,
      sym_expression,
    ACTIONS(23), 2,
      sym_number,
      sym_string,
    STATE(14), 5,
      sym_for_loop,
      sym_while_loop,
      sym_if_expression,
      sym_function_literal,
      sym_object,
  [1518] = 2,
    ACTIONS(197), 3,
      anon_sym_EQ,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(195), 17,
      anon_sym_SEMI,
      anon_sym_DOT,
      anon_sym_CARET,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_EQ_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_BANG_EQ,
      anon_sym_or,
      anon_sym_and,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
  [1543] = 2,
    ACTIONS(201), 3,
      anon_sym_EQ,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(199), 17,
      anon_sym_SEMI,
      anon_sym_DOT,
      anon_sym_CARET,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_EQ_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_BANG_EQ,
      anon_sym_or,
      anon_sym_and,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
  [1568] = 15,
    ACTIONS(7), 1,
      anon_sym_not,
    ACTIONS(9), 1,
      anon_sym_do,
    ACTIONS(11), 1,
      anon_sym_for,
    ACTIONS(13), 1,
      anon_sym_while,
    ACTIONS(15), 1,
      anon_sym_if,
    ACTIONS(17), 1,
      anon_sym_LBRACE,
    ACTIONS(19), 1,
      anon_sym_function,
    ACTIONS(21), 1,
      sym_identifier,
    STATE(13), 1,
      sym_literal,
    STATE(37), 1,
      sym_prefix,
    STATE(38), 1,
      sym_postfix,
    STATE(74), 1,
      sym_binary_expression,
    STATE(96), 1,
      sym_expression,
    ACTIONS(23), 2,
      sym_number,
      sym_string,
    STATE(14), 5,
      sym_for_loop,
      sym_while_loop,
      sym_if_expression,
      sym_function_literal,
      sym_object,
  [1619] = 2,
    ACTIONS(205), 3,
      anon_sym_EQ,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(203), 17,
      anon_sym_SEMI,
      anon_sym_DOT,
      anon_sym_CARET,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_EQ_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_BANG_EQ,
      anon_sym_or,
      anon_sym_and,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
  [1644] = 15,
    ACTIONS(7), 1,
      anon_sym_not,
    ACTIONS(9), 1,
      anon_sym_do,
    ACTIONS(11), 1,
      anon_sym_for,
    ACTIONS(13), 1,
      anon_sym_while,
    ACTIONS(15), 1,
      anon_sym_if,
    ACTIONS(17), 1,
      anon_sym_LBRACE,
    ACTIONS(19), 1,
      anon_sym_function,
    ACTIONS(21), 1,
      sym_identifier,
    STATE(13), 1,
      sym_literal,
    STATE(37), 1,
      sym_prefix,
    STATE(38), 1,
      sym_postfix,
    STATE(74), 1,
      sym_binary_expression,
    STATE(97), 1,
      sym_expression,
    ACTIONS(23), 2,
      sym_number,
      sym_string,
    STATE(14), 5,
      sym_for_loop,
      sym_while_loop,
      sym_if_expression,
      sym_function_literal,
      sym_object,
  [1695] = 13,
    ACTIONS(7), 1,
      anon_sym_not,
    ACTIONS(9), 1,
      anon_sym_do,
    ACTIONS(11), 1,
      anon_sym_for,
    ACTIONS(13), 1,
      anon_sym_while,
    ACTIONS(15), 1,
      anon_sym_if,
    ACTIONS(17), 1,
      anon_sym_LBRACE,
    ACTIONS(19), 1,
      anon_sym_function,
    ACTIONS(21), 1,
      sym_identifier,
    STATE(13), 1,
      sym_literal,
    STATE(38), 1,
      sym_postfix,
    STATE(67), 1,
      sym_prefix,
    ACTIONS(23), 2,
      sym_number,
      sym_string,
    STATE(14), 5,
      sym_for_loop,
      sym_while_loop,
      sym_if_expression,
      sym_function_literal,
      sym_object,
  [1740] = 13,
    ACTIONS(7), 1,
      anon_sym_not,
    ACTIONS(9), 1,
      anon_sym_do,
    ACTIONS(11), 1,
      anon_sym_for,
    ACTIONS(13), 1,
      anon_sym_while,
    ACTIONS(15), 1,
      anon_sym_if,
    ACTIONS(17), 1,
      anon_sym_LBRACE,
    ACTIONS(19), 1,
      anon_sym_function,
    ACTIONS(21), 1,
      sym_identifier,
    STATE(13), 1,
      sym_literal,
    STATE(38), 1,
      sym_postfix,
    STATE(68), 1,
      sym_prefix,
    ACTIONS(23), 2,
      sym_number,
      sym_string,
    STATE(14), 5,
      sym_for_loop,
      sym_while_loop,
      sym_if_expression,
      sym_function_literal,
      sym_object,
  [1785] = 13,
    ACTIONS(7), 1,
      anon_sym_not,
    ACTIONS(9), 1,
      anon_sym_do,
    ACTIONS(11), 1,
      anon_sym_for,
    ACTIONS(13), 1,
      anon_sym_while,
    ACTIONS(15), 1,
      anon_sym_if,
    ACTIONS(17), 1,
      anon_sym_LBRACE,
    ACTIONS(19), 1,
      anon_sym_function,
    ACTIONS(21), 1,
      sym_identifier,
    STATE(13), 1,
      sym_literal,
    STATE(38), 1,
      sym_postfix,
    STATE(69), 1,
      sym_prefix,
    ACTIONS(23), 2,
      sym_number,
      sym_string,
    STATE(14), 5,
      sym_for_loop,
      sym_while_loop,
      sym_if_expression,
      sym_function_literal,
      sym_object,
  [1830] = 13,
    ACTIONS(7), 1,
      anon_sym_not,
    ACTIONS(9), 1,
      anon_sym_do,
    ACTIONS(11), 1,
      anon_sym_for,
    ACTIONS(13), 1,
      anon_sym_while,
    ACTIONS(15), 1,
      anon_sym_if,
    ACTIONS(17), 1,
      anon_sym_LBRACE,
    ACTIONS(19), 1,
      anon_sym_function,
    ACTIONS(21), 1,
      sym_identifier,
    STATE(13), 1,
      sym_literal,
    STATE(38), 1,
      sym_postfix,
    STATE(72), 1,
      sym_prefix,
    ACTIONS(23), 2,
      sym_number,
      sym_string,
    STATE(14), 5,
      sym_for_loop,
      sym_while_loop,
      sym_if_expression,
      sym_function_literal,
      sym_object,
  [1875] = 13,
    ACTIONS(7), 1,
      anon_sym_not,
    ACTIONS(9), 1,
      anon_sym_do,
    ACTIONS(11), 1,
      anon_sym_for,
    ACTIONS(13), 1,
      anon_sym_while,
    ACTIONS(15), 1,
      anon_sym_if,
    ACTIONS(17), 1,
      anon_sym_LBRACE,
    ACTIONS(19), 1,
      anon_sym_function,
    ACTIONS(21), 1,
      sym_identifier,
    STATE(13), 1,
      sym_literal,
    STATE(38), 1,
      sym_postfix,
    STATE(70), 1,
      sym_prefix,
    ACTIONS(23), 2,
      sym_number,
      sym_string,
    STATE(14), 5,
      sym_for_loop,
      sym_while_loop,
      sym_if_expression,
      sym_function_literal,
      sym_object,
  [1920] = 13,
    ACTIONS(7), 1,
      anon_sym_not,
    ACTIONS(9), 1,
      anon_sym_do,
    ACTIONS(11), 1,
      anon_sym_for,
    ACTIONS(13), 1,
      anon_sym_while,
    ACTIONS(15), 1,
      anon_sym_if,
    ACTIONS(17), 1,
      anon_sym_LBRACE,
    ACTIONS(19), 1,
      anon_sym_function,
    ACTIONS(21), 1,
      sym_identifier,
    STATE(13), 1,
      sym_literal,
    STATE(38), 1,
      sym_postfix,
    STATE(71), 1,
      sym_prefix,
    ACTIONS(23), 2,
      sym_number,
      sym_string,
    STATE(14), 5,
      sym_for_loop,
      sym_while_loop,
      sym_if_expression,
      sym_function_literal,
      sym_object,
  [1965] = 11,
    ACTIONS(9), 1,
      anon_sym_do,
    ACTIONS(11), 1,
      anon_sym_for,
    ACTIONS(13), 1,
      anon_sym_while,
    ACTIONS(15), 1,
      anon_sym_if,
    ACTIONS(17), 1,
      anon_sym_LBRACE,
    ACTIONS(19), 1,
      anon_sym_function,
    ACTIONS(21), 1,
      sym_identifier,
    STATE(13), 1,
      sym_literal,
    STATE(43), 1,
      sym_postfix,
    ACTIONS(23), 2,
      sym_number,
      sym_string,
    STATE(14), 5,
      sym_for_loop,
      sym_while_loop,
      sym_if_expression,
      sym_function_literal,
      sym_object,
  [2004] = 2,
    ACTIONS(207), 5,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym_number,
      sym_string,
    ACTIONS(209), 9,
      anon_sym_let,
      anon_sym_return,
      anon_sym_not,
      anon_sym_do,
      anon_sym_for,
      anon_sym_while,
      anon_sym_if,
      anon_sym_function,
      sym_identifier,
  [2023] = 4,
    STATE(58), 1,
      sym_type_literal,
    STATE(75), 1,
      sym_union_type,
    STATE(105), 1,
      sym_type,
    ACTIONS(211), 3,
      sym_identifier,
      sym_number,
      sym_string,
  [2038] = 4,
    STATE(58), 1,
      sym_type_literal,
    STATE(75), 1,
      sym_union_type,
    STATE(101), 1,
      sym_type,
    ACTIONS(211), 3,
      sym_identifier,
      sym_number,
      sym_string,
  [2053] = 4,
    STATE(58), 1,
      sym_type_literal,
    STATE(75), 1,
      sym_union_type,
    STATE(81), 1,
      sym_type,
    ACTIONS(211), 3,
      sym_identifier,
      sym_number,
      sym_string,
  [2068] = 3,
    ACTIONS(215), 1,
      anon_sym_PIPE,
    STATE(59), 1,
      aux_sym_union_type_repeat1,
    ACTIONS(213), 4,
      anon_sym_EQ,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
  [2081] = 3,
    ACTIONS(215), 1,
      anon_sym_PIPE,
    STATE(61), 1,
      aux_sym_union_type_repeat1,
    ACTIONS(217), 4,
      anon_sym_EQ,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
  [2094] = 4,
    STATE(58), 1,
      sym_type_literal,
    STATE(75), 1,
      sym_union_type,
    STATE(126), 1,
      sym_type,
    ACTIONS(211), 3,
      sym_identifier,
      sym_number,
      sym_string,
  [2109] = 3,
    ACTIONS(221), 1,
      anon_sym_PIPE,
    STATE(61), 1,
      aux_sym_union_type_repeat1,
    ACTIONS(219), 4,
      anon_sym_EQ,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
  [2122] = 4,
    STATE(58), 1,
      sym_type_literal,
    STATE(75), 1,
      sym_union_type,
    STATE(102), 1,
      sym_type,
    ACTIONS(211), 3,
      sym_identifier,
      sym_number,
      sym_string,
  [2137] = 4,
    STATE(58), 1,
      sym_type_literal,
    STATE(75), 1,
      sym_union_type,
    STATE(103), 1,
      sym_type,
    ACTIONS(211), 3,
      sym_identifier,
      sym_number,
      sym_string,
  [2152] = 4,
    STATE(58), 1,
      sym_type_literal,
    STATE(75), 1,
      sym_union_type,
    STATE(104), 1,
      sym_type,
    ACTIONS(211), 3,
      sym_identifier,
      sym_number,
      sym_string,
  [2167] = 1,
    ACTIONS(224), 5,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
  [2175] = 1,
    ACTIONS(219), 5,
      anon_sym_EQ,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_PIPE,
  [2183] = 1,
    ACTIONS(224), 5,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
  [2191] = 1,
    ACTIONS(224), 5,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
  [2199] = 1,
    ACTIONS(224), 5,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
  [2207] = 1,
    ACTIONS(224), 5,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
  [2215] = 1,
    ACTIONS(224), 5,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
  [2223] = 1,
    ACTIONS(224), 5,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
  [2231] = 1,
    ACTIONS(226), 5,
      anon_sym_EQ,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_PIPE,
  [2239] = 1,
    ACTIONS(169), 5,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
  [2247] = 1,
    ACTIONS(213), 4,
      anon_sym_EQ,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
  [2254] = 2,
    STATE(66), 1,
      sym_type_literal,
    ACTIONS(211), 3,
      sym_identifier,
      sym_number,
      sym_string,
  [2263] = 3,
    ACTIONS(228), 1,
      anon_sym_COMMA,
    ACTIONS(230), 1,
      anon_sym_RPAREN,
    STATE(82), 1,
      aux_sym_postfix_repeat1,
  [2273] = 3,
    ACTIONS(232), 1,
      anon_sym_COMMA,
    ACTIONS(234), 1,
      anon_sym_RBRACE,
    STATE(87), 1,
      aux_sym_object_repeat1,
  [2283] = 3,
    ACTIONS(236), 1,
      anon_sym_if,
    ACTIONS(238), 1,
      anon_sym_LBRACE,
    STATE(22), 1,
      sym_block,
  [2293] = 3,
    ACTIONS(240), 1,
      anon_sym_COMMA,
    ACTIONS(243), 1,
      anon_sym_RPAREN,
    STATE(80), 1,
      aux_sym_postfix_repeat1,
  [2303] = 3,
    ACTIONS(245), 1,
      anon_sym_COMMA,
    ACTIONS(247), 1,
      anon_sym_RPAREN,
    STATE(83), 1,
      aux_sym_function_literal_repeat1,
  [2313] = 3,
    ACTIONS(147), 1,
      anon_sym_RPAREN,
    ACTIONS(249), 1,
      anon_sym_COMMA,
    STATE(80), 1,
      aux_sym_postfix_repeat1,
  [2323] = 3,
    ACTIONS(251), 1,
      anon_sym_COMMA,
    ACTIONS(253), 1,
      anon_sym_RPAREN,
    STATE(86), 1,
      aux_sym_function_literal_repeat1,
  [2333] = 3,
    ACTIONS(255), 1,
      anon_sym_COMMA,
    ACTIONS(257), 1,
      anon_sym_RBRACE,
    STATE(78), 1,
      aux_sym_object_repeat1,
  [2343] = 3,
    ACTIONS(236), 1,
      anon_sym_if,
    ACTIONS(238), 1,
      anon_sym_LBRACE,
    STATE(18), 1,
      sym_block,
  [2353] = 3,
    ACTIONS(259), 1,
      anon_sym_COMMA,
    ACTIONS(262), 1,
      anon_sym_RPAREN,
    STATE(86), 1,
      aux_sym_function_literal_repeat1,
  [2363] = 3,
    ACTIONS(264), 1,
      anon_sym_COMMA,
    ACTIONS(267), 1,
      anon_sym_RBRACE,
    STATE(87), 1,
      aux_sym_object_repeat1,
  [2373] = 2,
    ACTIONS(269), 1,
      anon_sym_RPAREN,
    ACTIONS(271), 1,
      sym_identifier,
  [2380] = 2,
    ACTIONS(273), 1,
      anon_sym_RPAREN,
    ACTIONS(275), 1,
      sym_identifier,
  [2387] = 2,
    ACTIONS(238), 1,
      anon_sym_LBRACE,
    STATE(11), 1,
      sym_block,
  [2394] = 2,
    ACTIONS(238), 1,
      anon_sym_LBRACE,
    STATE(19), 1,
      sym_block,
  [2401] = 2,
    ACTIONS(277), 1,
      anon_sym_RBRACE,
    ACTIONS(279), 1,
      sym_identifier,
  [2408] = 2,
    ACTIONS(281), 1,
      anon_sym_RBRACE,
    ACTIONS(283), 1,
      sym_identifier,
  [2415] = 2,
    ACTIONS(253), 1,
      anon_sym_RPAREN,
    ACTIONS(271), 1,
      sym_identifier,
  [2422] = 2,
    ACTIONS(238), 1,
      anon_sym_LBRACE,
    STATE(12), 1,
      sym_block,
  [2429] = 2,
    ACTIONS(238), 1,
      anon_sym_LBRACE,
    STATE(17), 1,
      sym_block,
  [2436] = 1,
    ACTIONS(243), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [2441] = 2,
    ACTIONS(238), 1,
      anon_sym_LBRACE,
    STATE(6), 1,
      sym_block,
  [2448] = 2,
    ACTIONS(234), 1,
      anon_sym_RBRACE,
    ACTIONS(279), 1,
      sym_identifier,
  [2455] = 1,
    ACTIONS(285), 2,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [2460] = 2,
    ACTIONS(238), 1,
      anon_sym_LBRACE,
    STATE(24), 1,
      sym_block,
  [2467] = 2,
    ACTIONS(238), 1,
      anon_sym_LBRACE,
    STATE(27), 1,
      sym_block,
  [2474] = 2,
    ACTIONS(238), 1,
      anon_sym_LBRACE,
    STATE(28), 1,
      sym_block,
  [2481] = 1,
    ACTIONS(287), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [2486] = 2,
    ACTIONS(238), 1,
      anon_sym_LBRACE,
    STATE(29), 1,
      sym_block,
  [2493] = 2,
    ACTIONS(289), 1,
      anon_sym_COLON,
    ACTIONS(291), 1,
      anon_sym_EQ,
  [2500] = 1,
    ACTIONS(293), 1,
      sym_identifier,
  [2504] = 1,
    ACTIONS(236), 1,
      anon_sym_if,
  [2508] = 1,
    ACTIONS(295), 1,
      anon_sym_SEMI,
  [2512] = 1,
    ACTIONS(297), 1,
      anon_sym_EQ,
  [2516] = 1,
    ACTIONS(279), 1,
      sym_identifier,
  [2520] = 1,
    ACTIONS(299), 1,
      anon_sym_COLON,
  [2524] = 1,
    ACTIONS(301), 1,
      anon_sym_COLON,
  [2528] = 1,
    ACTIONS(303), 1,
      anon_sym_SEMI,
  [2532] = 1,
    ACTIONS(305), 1,
      anon_sym_SEMI,
  [2536] = 1,
    ACTIONS(307), 1,
      anon_sym_LPAREN,
  [2540] = 1,
    ACTIONS(309), 1,
      anon_sym_SEMI,
  [2544] = 1,
    ACTIONS(311), 1,
      anon_sym_in,
  [2548] = 1,
    ACTIONS(313), 1,
      ts_builtin_sym_end,
  [2552] = 1,
    ACTIONS(315), 1,
      ts_builtin_sym_end,
  [2556] = 1,
    ACTIONS(317), 1,
      anon_sym_COLON,
  [2560] = 1,
    ACTIONS(271), 1,
      sym_identifier,
  [2564] = 1,
    ACTIONS(319), 1,
      anon_sym_COLON,
  [2568] = 1,
    ACTIONS(321), 1,
      anon_sym_COLON,
  [2572] = 1,
    ACTIONS(323), 1,
      sym_identifier,
  [2576] = 1,
    ACTIONS(325), 1,
      anon_sym_EQ,
  [2580] = 1,
    ACTIONS(327), 1,
      anon_sym_EQ,
  [2584] = 1,
    ACTIONS(329), 1,
      sym_identifier,
  [2588] = 1,
    ACTIONS(331), 1,
      anon_sym_COLON,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 67,
  [SMALL_STATE(4)] = 133,
  [SMALL_STATE(5)] = 199,
  [SMALL_STATE(6)] = 265,
  [SMALL_STATE(7)] = 297,
  [SMALL_STATE(8)] = 329,
  [SMALL_STATE(9)] = 361,
  [SMALL_STATE(10)] = 388,
  [SMALL_STATE(11)] = 415,
  [SMALL_STATE(12)] = 442,
  [SMALL_STATE(13)] = 468,
  [SMALL_STATE(14)] = 496,
  [SMALL_STATE(15)] = 522,
  [SMALL_STATE(16)] = 576,
  [SMALL_STATE(17)] = 602,
  [SMALL_STATE(18)] = 628,
  [SMALL_STATE(19)] = 654,
  [SMALL_STATE(20)] = 680,
  [SMALL_STATE(21)] = 706,
  [SMALL_STATE(22)] = 760,
  [SMALL_STATE(23)] = 786,
  [SMALL_STATE(24)] = 812,
  [SMALL_STATE(25)] = 838,
  [SMALL_STATE(26)] = 892,
  [SMALL_STATE(27)] = 918,
  [SMALL_STATE(28)] = 944,
  [SMALL_STATE(29)] = 970,
  [SMALL_STATE(30)] = 996,
  [SMALL_STATE(31)] = 1047,
  [SMALL_STATE(32)] = 1098,
  [SMALL_STATE(33)] = 1149,
  [SMALL_STATE(34)] = 1200,
  [SMALL_STATE(35)] = 1251,
  [SMALL_STATE(36)] = 1302,
  [SMALL_STATE(37)] = 1327,
  [SMALL_STATE(38)] = 1366,
  [SMALL_STATE(39)] = 1391,
  [SMALL_STATE(40)] = 1416,
  [SMALL_STATE(41)] = 1467,
  [SMALL_STATE(42)] = 1518,
  [SMALL_STATE(43)] = 1543,
  [SMALL_STATE(44)] = 1568,
  [SMALL_STATE(45)] = 1619,
  [SMALL_STATE(46)] = 1644,
  [SMALL_STATE(47)] = 1695,
  [SMALL_STATE(48)] = 1740,
  [SMALL_STATE(49)] = 1785,
  [SMALL_STATE(50)] = 1830,
  [SMALL_STATE(51)] = 1875,
  [SMALL_STATE(52)] = 1920,
  [SMALL_STATE(53)] = 1965,
  [SMALL_STATE(54)] = 2004,
  [SMALL_STATE(55)] = 2023,
  [SMALL_STATE(56)] = 2038,
  [SMALL_STATE(57)] = 2053,
  [SMALL_STATE(58)] = 2068,
  [SMALL_STATE(59)] = 2081,
  [SMALL_STATE(60)] = 2094,
  [SMALL_STATE(61)] = 2109,
  [SMALL_STATE(62)] = 2122,
  [SMALL_STATE(63)] = 2137,
  [SMALL_STATE(64)] = 2152,
  [SMALL_STATE(65)] = 2167,
  [SMALL_STATE(66)] = 2175,
  [SMALL_STATE(67)] = 2183,
  [SMALL_STATE(68)] = 2191,
  [SMALL_STATE(69)] = 2199,
  [SMALL_STATE(70)] = 2207,
  [SMALL_STATE(71)] = 2215,
  [SMALL_STATE(72)] = 2223,
  [SMALL_STATE(73)] = 2231,
  [SMALL_STATE(74)] = 2239,
  [SMALL_STATE(75)] = 2247,
  [SMALL_STATE(76)] = 2254,
  [SMALL_STATE(77)] = 2263,
  [SMALL_STATE(78)] = 2273,
  [SMALL_STATE(79)] = 2283,
  [SMALL_STATE(80)] = 2293,
  [SMALL_STATE(81)] = 2303,
  [SMALL_STATE(82)] = 2313,
  [SMALL_STATE(83)] = 2323,
  [SMALL_STATE(84)] = 2333,
  [SMALL_STATE(85)] = 2343,
  [SMALL_STATE(86)] = 2353,
  [SMALL_STATE(87)] = 2363,
  [SMALL_STATE(88)] = 2373,
  [SMALL_STATE(89)] = 2380,
  [SMALL_STATE(90)] = 2387,
  [SMALL_STATE(91)] = 2394,
  [SMALL_STATE(92)] = 2401,
  [SMALL_STATE(93)] = 2408,
  [SMALL_STATE(94)] = 2415,
  [SMALL_STATE(95)] = 2422,
  [SMALL_STATE(96)] = 2429,
  [SMALL_STATE(97)] = 2436,
  [SMALL_STATE(98)] = 2441,
  [SMALL_STATE(99)] = 2448,
  [SMALL_STATE(100)] = 2455,
  [SMALL_STATE(101)] = 2460,
  [SMALL_STATE(102)] = 2467,
  [SMALL_STATE(103)] = 2474,
  [SMALL_STATE(104)] = 2481,
  [SMALL_STATE(105)] = 2486,
  [SMALL_STATE(106)] = 2493,
  [SMALL_STATE(107)] = 2500,
  [SMALL_STATE(108)] = 2504,
  [SMALL_STATE(109)] = 2508,
  [SMALL_STATE(110)] = 2512,
  [SMALL_STATE(111)] = 2516,
  [SMALL_STATE(112)] = 2520,
  [SMALL_STATE(113)] = 2524,
  [SMALL_STATE(114)] = 2528,
  [SMALL_STATE(115)] = 2532,
  [SMALL_STATE(116)] = 2536,
  [SMALL_STATE(117)] = 2540,
  [SMALL_STATE(118)] = 2544,
  [SMALL_STATE(119)] = 2548,
  [SMALL_STATE(120)] = 2552,
  [SMALL_STATE(121)] = 2556,
  [SMALL_STATE(122)] = 2560,
  [SMALL_STATE(123)] = 2564,
  [SMALL_STATE(124)] = 2568,
  [SMALL_STATE(125)] = 2572,
  [SMALL_STATE(126)] = 2576,
  [SMALL_STATE(127)] = 2580,
  [SMALL_STATE(128)] = 2584,
  [SMALL_STATE(129)] = 2588,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = false}}, SHIFT(125),
  [5] = {.entry = {.count = 1, .reusable = false}}, SHIFT(33),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(53),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(95),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(128),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(44),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(30),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(93),
  [19] = {.entry = {.count = 1, .reusable = false}}, SHIFT(116),
  [21] = {.entry = {.count = 1, .reusable = false}}, SHIFT(14),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [25] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_program_repeat1, 2, 0, 0),
  [27] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_program_repeat1, 2, 0, 0), SHIFT_REPEAT(125),
  [30] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_program_repeat1, 2, 0, 0), SHIFT_REPEAT(33),
  [33] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_program_repeat1, 2, 0, 0), SHIFT_REPEAT(53),
  [36] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_program_repeat1, 2, 0, 0), SHIFT_REPEAT(95),
  [39] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_program_repeat1, 2, 0, 0), SHIFT_REPEAT(128),
  [42] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_program_repeat1, 2, 0, 0), SHIFT_REPEAT(44),
  [45] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_program_repeat1, 2, 0, 0), SHIFT_REPEAT(30),
  [48] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_program_repeat1, 2, 0, 0), SHIFT_REPEAT(93),
  [51] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_program_repeat1, 2, 0, 0), SHIFT_REPEAT(116),
  [54] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_program_repeat1, 2, 0, 0), SHIFT_REPEAT(14),
  [57] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_program_repeat1, 2, 0, 0), SHIFT_REPEAT(14),
  [60] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [62] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_program, 1, 0, 0),
  [64] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [66] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_if_expression, 3, 0, 0),
  [68] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_if_expression, 3, 0, 0),
  [70] = {.entry = {.count = 1, .reusable = true}}, SHIFT(85),
  [72] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_if_expression, 4, 0, 0),
  [74] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_if_expression, 4, 0, 0),
  [76] = {.entry = {.count = 1, .reusable = true}}, SHIFT(79),
  [78] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_if_expression_repeat1, 2, 0, 0),
  [80] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_if_expression_repeat1, 2, 0, 0),
  [82] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_if_expression_repeat1, 2, 0, 0), SHIFT_REPEAT(108),
  [85] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 2, 0, 0),
  [87] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block, 2, 0, 0),
  [89] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 3, 0, 0),
  [91] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block, 3, 0, 0),
  [93] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_if_expression_repeat1, 4, 0, 0),
  [95] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_if_expression_repeat1, 4, 0, 0),
  [97] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_literal, 2, 0, 0),
  [99] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_literal, 2, 0, 0),
  [101] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_postfix, 1, 0, 0),
  [103] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_postfix, 1, 0, 0),
  [105] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [107] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_literal, 1, 0, 0),
  [109] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_literal, 1, 0, 0),
  [111] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [113] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_object, 2, 0, 0),
  [115] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_object, 2, 0, 0),
  [117] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_while_loop, 3, 0, 0),
  [119] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_while_loop, 3, 0, 0),
  [121] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_if_expression, 5, 0, 0),
  [123] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_if_expression, 5, 0, 0),
  [125] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_for_loop, 5, 0, 0),
  [127] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_for_loop, 5, 0, 0),
  [129] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_object, 5, 0, 0),
  [131] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_object, 5, 0, 0),
  [133] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [135] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_if_expression, 6, 0, 0),
  [137] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_if_expression, 6, 0, 0),
  [139] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_object, 6, 0, 0),
  [141] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_object, 6, 0, 0),
  [143] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_literal, 6, 0, 0),
  [145] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function_literal, 6, 0, 0),
  [147] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [149] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_object, 7, 0, 0),
  [151] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_object, 7, 0, 0),
  [153] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_literal, 9, 0, 0),
  [155] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function_literal, 9, 0, 0),
  [157] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_literal, 10, 0, 0),
  [159] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function_literal, 10, 0, 0),
  [161] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_literal, 11, 0, 0),
  [163] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function_literal, 11, 0, 0),
  [165] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_postfix, 3, 0, 0),
  [167] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_postfix, 3, 0, 0),
  [169] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression, 1, 0, 0),
  [171] = {.entry = {.count = 1, .reusable = false}}, SHIFT(47),
  [173] = {.entry = {.count = 1, .reusable = true}}, SHIFT(107),
  [175] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [177] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [179] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [181] = {.entry = {.count = 1, .reusable = false}}, SHIFT(51),
  [183] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [185] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [187] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_prefix, 1, 0, 0),
  [189] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_prefix, 1, 0, 0),
  [191] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_postfix, 4, 0, 0),
  [193] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_postfix, 4, 0, 0),
  [195] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_postfix, 5, 0, 0),
  [197] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_postfix, 5, 0, 0),
  [199] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_prefix, 2, 0, 0),
  [201] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_prefix, 2, 0, 0),
  [203] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_postfix, 6, 0, 0),
  [205] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_postfix, 6, 0, 0),
  [207] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_statement, 2, 0, 0),
  [209] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_statement, 2, 0, 0),
  [211] = {.entry = {.count = 1, .reusable = true}}, SHIFT(73),
  [213] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type, 1, 0, 0),
  [215] = {.entry = {.count = 1, .reusable = true}}, SHIFT(76),
  [217] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_union_type, 2, 0, 0),
  [219] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_union_type_repeat1, 2, 0, 0),
  [221] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_union_type_repeat1, 2, 0, 0), SHIFT_REPEAT(76),
  [224] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_binary_expression, 3, 0, 0),
  [226] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_literal, 1, 0, 0),
  [228] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [230] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [232] = {.entry = {.count = 1, .reusable = true}}, SHIFT(92),
  [234] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [236] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [238] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [240] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_postfix_repeat1, 2, 0, 0), SHIFT_REPEAT(46),
  [243] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_postfix_repeat1, 2, 0, 0),
  [245] = {.entry = {.count = 1, .reusable = true}}, SHIFT(94),
  [247] = {.entry = {.count = 1, .reusable = true}}, SHIFT(123),
  [249] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [251] = {.entry = {.count = 1, .reusable = true}}, SHIFT(88),
  [253] = {.entry = {.count = 1, .reusable = true}}, SHIFT(112),
  [255] = {.entry = {.count = 1, .reusable = true}}, SHIFT(99),
  [257] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [259] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_function_literal_repeat1, 2, 0, 0), SHIFT_REPEAT(122),
  [262] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_function_literal_repeat1, 2, 0, 0),
  [264] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_object_repeat1, 2, 0, 0), SHIFT_REPEAT(111),
  [267] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_object_repeat1, 2, 0, 0),
  [269] = {.entry = {.count = 1, .reusable = true}}, SHIFT(121),
  [271] = {.entry = {.count = 1, .reusable = true}}, SHIFT(113),
  [273] = {.entry = {.count = 1, .reusable = true}}, SHIFT(124),
  [275] = {.entry = {.count = 1, .reusable = true}}, SHIFT(129),
  [277] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [279] = {.entry = {.count = 1, .reusable = true}}, SHIFT(110),
  [281] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [283] = {.entry = {.count = 1, .reusable = true}}, SHIFT(127),
  [285] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_object_repeat1, 4, 0, 0),
  [287] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_function_literal_repeat1, 4, 0, 0),
  [289] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [291] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [293] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [295] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_declaration, 6, 0, 0),
  [297] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [299] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [301] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [303] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_declaration, 4, 0, 0),
  [305] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_return_statement, 2, 0, 0),
  [307] = {.entry = {.count = 1, .reusable = true}}, SHIFT(89),
  [309] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [311] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [313] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [315] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [317] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [319] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [321] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [323] = {.entry = {.count = 1, .reusable = true}}, SHIFT(106),
  [325] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [327] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [329] = {.entry = {.count = 1, .reusable = true}}, SHIFT(118),
  [331] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_klein(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
